### ISSUE TITLE
Travis build fails on node 4.0 / 4.1

### ISSUE THREAD

**Issue by Toub** [toubiweb/lwip-jpeg-autorotate#3]
It fails during lwip install: https://travis-ci.org/toubiweb/lwip-jpeg-autorotate/jobs/83858628

Probably due to pre-requisites missing: https://github.com/EyalAr/lwip (lwip travis build install g++ 4.8).

**Comment by Toub** [comment]
Looks like a problem with nan: 
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);

Will try to upgrade to lwip 0.0.8 as nan has been upgraded too.

**Comment by simison** [comment]
Here's my setup for Node v4, pretty much taken from meanjs:

https://github.com/Trustroots/trustroots/blob/master/.travis.yml

**Comment by Toub** [comment]
Thanks @simison 
Upgrading to lwip 0.0.8 fixed the problem.
