### ISSUE TITLE
bump lwip version

### ISSUE THREAD

**Issue by retrojorgen** [toubiweb/lwip-jpeg-autorotate#4]
Hi! Can we bump the lwip dependency to 0.0.9 instead of 8? It seems to be crashing on my machine

Details:
Mac OS El Capitan
Xcode 8
Node 4.20

error:

3 warnings and 4 errors generated.
make: **\* [Release/obj.target/lwip_decoder/src/decoder/init.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jorjacob/Repos/samlenett/node_modules/lwip-jpeg-autorotate/node_modules/lwip
gyp ERR! node -v v6.8.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-S" "lwip-jpeg-autorotate"
npm ERR! node v6.8.1
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! lwip@0.0.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lwip@0.0.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the lwip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lwip
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls lwip
npm ERR! There is likely additional logging output above.

**Comment by Toub** [comment]
I just released a new version, please upgrade:
```bash
npm install --save lwip-jpeg-autorotate@0.1.2
```

**Comment by Toub** [comment]
But you should probably use this package indeed: https://github.com/johansatge/jpeg-autorotate
